// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {

    ext {
        kotlinVersion = "2.0.20"
        kotlinGradlePluginVersion = '8.6.0'
        koinVersion = "3.4.3"
        composeVersion = "1.7.6"
        composeCompilerVersion = "1.5.15"
        androidActivityComposeVersion = "1.9.3"

        bugsnagGradlePluginVersion = "7.2.0"
        bugsnagAndroidVersion = "5.31.1"
    }

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$kotlinGradlePluginVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:$bugsnagGradlePluginVersion"
        classpath 'org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.0.20'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}